# Generated by Django 4.1.2 on 2022-10-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forget_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_logout_time',
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
