# Generated by Django 4.1.2 on 2022-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_books_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.AddField(
            model_name='store',
            name='visitors',
            field=models.ManyToManyField(to='accounts.employee'),
        ),
    ]
